* compilation fails in ml_term_manager.c by configure --disable-fribidi because of   undefined reference to ml_bidi_set_base_dir().   (Thanks to Nanashi san) * only limited region is scrolled when output characters is over screen buffer. * -J,--rtl,bidi_base_direction_rtl option is dynamically changeable.